// Generates supabase/seed.sql — roles, permissions, settings, demo catalogue & content.
// Run: node scripts/generate-seed.mjs
// All demo content can be edited or removed from the admin dashboard.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const out = [];
const sql = (s) => out.push(s.trim() + '\n');
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (a) => `array[${a.map(q).join(',')}]::text[]`;
const N = (naira) => Math.round(naira * 100); // naira -> kobo

sql(`-- HairverGreen seed data (generated by scripts/generate-seed.mjs). Safe to run once on a fresh database.
set search_path = public, extensions;`);

// ---------------------------------------------------------------------------
// Permissions & roles
// ---------------------------------------------------------------------------
const PERMS = {
  dashboard: [['dashboard.view', 'View the admin dashboard']],
  products: [
    ['products.view', 'View products'], ['products.create', 'Create products'], ['products.edit', 'Edit products'],
    ['products.delete', 'Delete products'], ['products.publish', 'Publish / unpublish products'],
    ['categories.manage', 'Manage categories & attributes'], ['collections.manage', 'Manage collections'],
    ['bundles.manage', 'Manage bundles'],
  ],
  inventory: [['inventory.view', 'View inventory'], ['inventory.edit', 'Adjust stock']],
  orders: [
    ['orders.view', 'View orders'], ['orders.edit', 'Update orders, fulfilment & tracking'], ['orders.refund', 'Issue refunds'],
    ['orders.cancel', 'Cancel orders'], ['orders.export', 'Export orders'], ['returns.manage', 'Manage returns & exchanges'],
  ],
  customers: [['customers.view', 'View customers'], ['customers.edit', 'Edit customers'], ['customers.export', 'Export customers']],
  marketing: [
    ['coupons.create', 'Create discounts & coupons'], ['coupons.edit', 'Edit discounts & coupons'], ['coupons.delete', 'Delete discounts & coupons'],
    ['campaigns.manage', 'Manage sales campaigns'], ['popups.manage', 'Manage popups & announcement bar'],
    ['newsletter.view', 'View newsletter subscribers'], ['carts.view', 'View abandoned carts'],
  ],
  reviews: [['reviews.moderate', 'Approve, hide & respond to reviews']],
  content: [
    ['content.create', 'Create pages & sections'], ['content.edit', 'Edit pages, homepage & sections'], ['content.publish', 'Publish pages'],
    ['navigation.manage', 'Manage navigation menus'], ['social.manage', 'Manage social gallery'],
  ],
  blog: [
    ['blog.create', 'Create journal posts'], ['blog.edit_own', 'Edit own posts'], ['blog.edit_any', 'Edit any post'], ['blog.publish', 'Publish posts'],
  ],
  media: [['media.upload', 'Upload media'], ['media.delete', 'Delete media']],
  services: [['consultations.manage', 'Manage consultations & custom-unit requests'], ['messages.view', 'View contact messages']],
  operations: [['shipping.manage', 'Manage shipping zones & rates'], ['taxes.manage', 'Manage tax rules'], ['payments.view', 'View payment transactions']],
  analytics: [['analytics.view', 'View sales analytics'], ['finance.view', 'View profit & margins'], ['expenses.manage', 'Record business expenses']],
  settings: [['settings.edit', 'Edit store settings & integrations'], ['theme.edit', 'Edit theme & branding']],
  admin: [['users.manage', 'Manage staff accounts'], ['roles.manage', 'Manage roles & permissions'], ['audit.view', 'View audit log']],
};
const allPerms = Object.entries(PERMS).flatMap(([g, ps]) => ps.map(([k, d]) => ({ k, d, g })));
sql(`insert into public.permissions (key, grp, description) values\n${allPerms.map((p) => `(${q(p.k)}, ${q(p.g)}, ${q(p.d)})`).join(',\n')};`);

const roles = [
  ['super_admin', 'Super Admin', 'Full access to everything, including staff, roles and settings.', allPerms.map((p) => p.k)],
  ['admin', 'Admin', 'Runs day-to-day ecommerce. Cannot manage staff, roles or core settings unless granted.',
    allPerms.map((p) => p.k).filter((k) => !['users.manage', 'roles.manage', 'settings.edit'].includes(k))],
  ['editor', 'Editor', 'Manages pages, homepage, journal, banners, collections, navigation, media and SEO.',
    ['dashboard.view', 'products.view', 'collections.manage', 'content.create', 'content.edit', 'content.publish', 'navigation.manage',
      'social.manage', 'blog.create', 'blog.edit_own', 'blog.edit_any', 'blog.publish', 'media.upload', 'popups.manage', 'theme.edit']],
  ['author', 'Author', 'Writes journal posts and uploads media. Publishing is configurable.',
    ['dashboard.view', 'blog.create', 'blog.edit_own', 'media.upload']],
  ['fulfilment', 'Fulfilment', 'Processes and ships orders, handles returns and stock.',
    ['dashboard.view', 'orders.view', 'orders.edit', 'returns.manage', 'inventory.view', 'inventory.edit', 'products.view', 'customers.view', 'consultations.manage']],
];
for (const [key, name, desc, perms] of roles) {
  sql(`with r as (insert into public.roles (key, name, description, is_system) values (${q(key)}, ${q(name)}, ${q(desc)}, true) returning id)
insert into public.role_permissions (role_id, permission_key) select r.id, k from r, unnest(${arr(perms)}) k;`);
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------
const settings = {
  store: [true, {
    name: 'Hairver Green', short_name: 'HairverGreen', tagline: 'Luxury Hair House · Lagos',
    email: 'hello@hairvergreen.com', phone: '', whatsapp: '', address: 'Lagos, Nigeria', city: 'Lagos', country: 'NG',
    instagram: 'https://www.instagram.com/hairvergreen/', tiktok: '', support_hours: 'Mon–Sat, 9am–6pm WAT',
  }],
  theme: [true, {
    colors: { primary: '#0F3D2E', primary_contrast: '#F6F2EA', accent: '#D8C08E', accent_strong: '#B0925C', background: '#F6F2EA', surface: '#FFFDF8', panel: '#EFE6D2', text: '#1B1A17', muted: '#6B665C', border: '#E3D9C4', sale: '#8A2E2E' },
    fonts: { display: 'Cormorant Garamond', body: 'Jost' },
    radius: 'none', button_style: 'solid', product_card: 'editorial', animations: 'subtle',
    logo_media_url: null, favicon_url: null,
  }],
  checkout: [true, { guest_checkout: true, hold_minutes: 60, require_phone: true, terms_page: '/policies/terms', order_note: true }],
  currencies: [true, { base: 'NGN', display: [
    { code: 'NGN', symbol: '₦', rate: 1 }, { code: 'USD', symbol: '$', rate: 1550 }, { code: 'GBP', symbol: '£', rate: 2050 }, { code: 'EUR', symbol: '€', rate: 1750 },
  ], note: 'rate = Naira per 1 unit of the currency. Display only — customers are always charged in NGN.' }],
  seo: [true, { title_template: '%s · Hairver Green', default_title: 'Hairver Green — Luxury Hair House, Lagos',
    default_description: 'Premium virgin hair, donor hair, custom units and ready-to-wear wigs, crafted in Lagos and delivered worldwide.', og_image: null }],
  analytics: [true, { ga4_id: '', meta_pixel_id: '', tiktok_pixel_id: '', gsc_verification: '' }],
  shipping: [true, { free_shipping_banner: true, origin_country: 'NG', origin_state: 'Lagos' }],
  notifications: [false, { order_alert_emails: [], low_stock_emails: [], from_name: 'Hairver Green' }],
  payments: [false, { providers: { paystack: { enabled: true, label: 'Card, bank transfer, USSD & more' } }, default_provider: 'paystack' }],
  social_proof: [true, { reviews_enabled: true, verified_only: false }],
};
sql(`insert into public.settings (key, value, is_public) values\n${Object.entries(settings).map(([k, [pub, v]]) => `(${q(k)}, ${j(v)}, ${pub})`).join(',\n')};`);

// ---------------------------------------------------------------------------
// Media (demo artwork)
// ---------------------------------------------------------------------------
const textures = ['straight', 'body-wave', 'loose-wave', 'deep-wave', 'curly', 'kinky'];
const mediaFiles = [];
for (const t of textures) for (let i = 1; i <= 4; i++) mediaFiles.push([`${t}-${i}.svg`, `${t.replace('-', ' ')} texture — demo artwork ${i}`]);
for (const f of ['hero', 'hero-mobile', 'editorial-1', 'editorial-2', 'editorial-3', 'custom-unit', 'journal-1', 'journal-2', 'journal-3', 'journal-4', 'care-kit', 'storage-bag'])
  mediaFiles.push([`${f}.svg`, `${f.replace(/-/g, ' ')} — demo artwork`]);
for (let i = 1; i <= 8; i++) mediaFiles.push([`social-${i}.svg`, `Social post ${i} — demo artwork`]);
sql(`insert into public.media_folders (name) values ('Demo artwork'), ('Products'), ('Editorial'), ('Journal');`);
sql(`insert into public.media (folder_id, url, filename, title, alt, kind, mime_type, width, height, tags)
select (select id from public.media_folders where name = 'Demo artwork'), '/demo/' || f, f, t, t, 'image', 'image/svg+xml',
  case when f like 'hero.svg' then 1920 when f like 'hero-mobile%' then 900 when f like 'editorial-2%' or f like 'custom-unit%' then 1600 when f like 'journal%' or f like 'editorial%' then 1200 when f like 'social%' then 900 else 800 end,
  case when f like 'hero.svg' then 1080 when f like 'hero-mobile%' then 1400 when f like 'editorial-2%' then 1000 when f like 'custom-unit%' then 1100 when f like 'journal%' then 800 when f like 'editorial%' then 1500 when f like 'social%' then 900 else 1000 end,
  array['demo']
from (values ${mediaFiles.map(([f, t]) => `(${q(f)}, ${q(t)})`).join(', ')}) v(f, t);`);
sql(`insert into public.media (folder_id, url, filename, title, alt, kind, mime_type, width, height, size_bytes, tags)
values ((select id from public.media_folders where name = 'Editorial'), '/hero/hero-curly.jpg', 'hero-curly.jpg', 'Hero — curly hair portrait', 'Model wearing voluminous curly hair', 'image', 'image/jpeg', 1800, 1200, 216727, array['hero']);`);
const M = (file) => `(select id from public.media where filename = ${q(file)})`;

// ---------------------------------------------------------------------------
// Attribute values
// ---------------------------------------------------------------------------
const attrs = {
  texture: [['Straight', 'straight'], ['Body Wave', 'body-wave'], ['Loose Wave', 'loose-wave'], ['Deep Wave', 'deep-wave'], ['Curly', 'curly'], ['Kinky', 'kinky']],
  length: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30].map((n) => [`${n}"`, String(n)]),
  color: [['Natural Black', 'natural-black', '#1b1512'], ['Chestnut Brown', 'chestnut-brown', '#5a3825'], ['Honey Blonde', 'honey-blonde', '#c9a26b'], ['Custom Colour', 'custom-colour', null]],
  lace: [['4×4 Closure', '4x4'], ['5×5 Closure', '5x5'], ['6×6 Closure', '6x6'], ['13×4 Frontal', '13x4'], ['13×6 Frontal', '13x6']],
  density: [['150%', '150'], ['180%', '180'], ['200%', '200'], ['220%', '220']],
  construction: [['Glueless', 'glueless'], ['Lace Front', 'lace-front'], ['Closure', 'closure'], ['Full Lace', 'full-lace'], ['V-Part', 'v-part'], ['Custom', 'custom']],
  cap_size: [['Small (21")', 'small'], ['Medium (22")', 'medium'], ['Large (23")', 'large']],
};
const texDesc = {
  straight: 'Silky, bone-straight fall with natural movement. Holds a sleek press and curls well with heat.',
  'body-wave': 'Soft S-pattern waves with volume at the ends. The most versatile texture — wear it wavy or press it straight.',
  'loose-wave': 'Relaxed, loose waves between body wave and deep wave. Effortless, lived-in volume.',
  'deep-wave': 'Defined, tight waves with bounce. Rich texture that reads full at every length.',
  curly: 'Springy, defined curls with softness. Best refreshed with water and a light leave-in.',
  kinky: 'Blends with relaxed and blow-dried natural hair. Textured, full and realistic.',
};
const attrRows = [];
for (const [a, vals] of Object.entries(attrs)) vals.forEach(([label, slug, sw], i) => attrRows.push(`(${q(a)}, ${q(label)}, ${q(slug)}, ${i}, ${q(sw ?? null)}, ${q(a === 'texture' ? texDesc[slug] : null)}, ${a === 'length' ? (Number(slug) <= 28 ? 'true' : 'false') : ['texture', 'length'].includes(a) ? 'true' : 'false'})`));
sql(`insert into public.attribute_values (attribute, label, slug, sort, swatch, description, show_in_nav) values\n${attrRows.join(',\n')};`);

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------
const cats = [
  ['Wigs', 'wigs', null, 'Ready-to-wear, glueless and lace units, finished by hand in Lagos.', 'editorial-3.svg'],
  ['Hair', 'hair', null, 'Virgin and donor hair in every texture, sold by the bundle, closure and frontal.', 'editorial-1.svg'],
  ['Care & Accessories', 'accessories', null, 'Everything you need to keep your hair beautiful for longer.', 'care-kit.svg'],
  ['Ready-to-Wear Wigs', 'ready-to-wear', 'wigs', 'Styled, plucked and ready the day it arrives.', 'body-wave-2.svg'],
  ['Glueless Wigs', 'glueless-wigs', 'wigs', 'Secure, adhesive-free units with adjustable bands.', 'straight-2.svg'],
  ['Lace Wigs', 'lace-wigs', 'wigs', 'HD lace fronts and full lace for the most natural hairline.', 'deep-wave-2.svg'],
  ['Custom Units', 'custom-units', 'wigs', 'Made to your measurements, texture and style.', 'custom-unit.svg'],
  ['Pre-Styled Units', 'pre-styled-units', 'wigs', 'Cut, coloured and styled by our team.', 'straight-4.svg'],
  ['Virgin Hair', 'virgin-hair', 'hair', 'Unprocessed virgin hair with the cuticle intact and aligned.', 'body-wave-1.svg'],
  ['Donor Hair', 'donor-hair', 'hair', 'Rare single-donor hair — the most refined hair we carry.', 'straight-1.svg'],
  ['Bundles', 'bundles', 'hair', 'Wefts sold per bundle, in lengths from 10" to 30".', 'loose-wave-1.svg'],
  ['Closures', 'closures', 'hair', 'HD lace closures for a flawless parting.', 'deep-wave-1.svg'],
  ['Frontals', 'frontals', 'hair', 'Ear-to-ear HD lace frontals.', 'deep-wave-3.svg'],
  ['Hair Extensions', 'hair-extensions', 'hair', 'Clip-ins and tape-ins for length and volume.', 'kinky-1.svg'],
];
cats.forEach(([name, slug, parent, desc, img], i) => sql(`insert into public.categories (name, slug, parent_id, description, image_id, sort, seo_title, seo_description)
values (${q(name)}, ${q(slug)}, ${parent ? `(select id from public.categories where slug = ${q(parent)})` : 'null'}, ${q(desc)}, ${M(img)}, ${i}, null, ${q(desc)});`));

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------
const care = '<p>Detangle gently from ends to roots with a wide-tooth comb. Co-wash every 7–10 wears with a sulphate-free shampoo and a moisturising conditioner. Let it air-dry flat or on a stand, and use a heat protectant before styling. Store in a silk bag, away from direct sunlight.</p>';
const shippingNote = 'In-stock items dispatch from Lagos within 1–2 business days. Custom units dispatch after production. Delivery times and fees are calculated at checkout for your address.';
const returnsNote = 'Unworn, unaltered hair with its lace and wefts intact can be returned or exchanged under our Returns Policy. For hygiene reasons, worn, cut, coloured or custom items cannot be returned.';
const faq = (extra = []) => [
  ...extra,
  { q: 'Can I colour or bleach this hair?', a: 'Yes — virgin and donor hair can be coloured by a professional. We recommend a strand test first. Coloured hair is not eligible for return.' },
  { q: 'How long will it last?', a: 'With the care routine above, our virgin hair typically lasts well over a year of regular wear. Donor hair lasts longer still.' },
];

const P = [];
function product(p) { P.push(p); }
const lengthPrice = (lengths, base, step) => Object.fromEntries(lengths.map((l, i) => [l, base + i * step]));

product({
  name: 'HairverGreen Signature Body Wave', slug: 'signature-body-wave', sku: 'HG-SBW', type: 'hair', cat: 'virgin-hair',
  short: 'Our signature virgin body wave — soft S-waves, full ends and a natural lustre. Sold per bundle.',
  desc: '<p>The texture we are known for. Signature Body Wave is unprocessed virgin hair with the cuticle intact and aligned, so it moves, shines and wears like your own. Double-wefted for fullness from root to end.</p><p>Wear the waves, or press it sleek — it returns to its pattern after washing.</p>',
  tags: ['bestseller', 'virgin', 'body wave', 'bundles'], featured: true, isNew: false,
  options: { texture: ['body-wave'], length: ['12', '14', '16', '18', '20', '22', '24', '26', '28', '30'] },
  price: (o) => lengthPrice(['12', '14', '16', '18', '20', '22', '24', '26', '28', '30'], N(85000), N(15000))[o.length],
  compare: (o) => (o.length === '30' ? N(245000) : null), stock: (o) => (o.length === '20' ? 3 : o.length === '30' ? 2 : 12),
  images: [['body-wave-1.svg'], ['body-wave-2.svg'], ['body-wave-3.svg'], ['body-wave-4.svg']], weight: 110,
  details: { origin: 'Ethically sourced virgin hair', grade: 'Signature', weight_per_bundle: '100g (±5g)', hair_info: 'Unprocessed, cuticle-aligned, double-wefted. Can be coloured, bleached and heat-styled.' },
  collections: ['best-sellers', 'signature'],
});
product({
  name: 'HairverGreen Luxury Straight', slug: 'luxury-straight', sku: 'HG-LST', type: 'hair', cat: 'virgin-hair',
  short: 'Bone-straight virgin hair with a silky fall and natural shine. Sold per bundle.',
  desc: '<p>Sleek, weightless and full to the ends. Luxury Straight is selected for thickness and uniformity, then double-wefted so every bundle sits flat and blends seamlessly.</p>',
  tags: ['bestseller', 'virgin', 'straight', 'bundles'], featured: true,
  options: { texture: ['straight'], length: ['10', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30'] },
  price: (o) => lengthPrice(['10', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30'], N(75000), N(15000))[o.length],
  stock: (o) => (o.length === '26' ? 0 : 10), images: [['straight-1.svg'], ['straight-2.svg'], ['straight-3.svg']], weight: 110,
  details: { origin: 'Ethically sourced virgin hair', grade: 'Luxury', weight_per_bundle: '100g (±5g)', hair_info: 'Unprocessed, cuticle-aligned, double-wefted.' },
  collections: ['best-sellers', 'luxury'],
});
product({
  name: 'HairverGreen Deep Wave', slug: 'deep-wave', sku: 'HG-DW', type: 'hair', cat: 'virgin-hair',
  short: 'Defined, bouncy deep waves with lasting pattern. Sold per bundle.',
  desc: '<p>Rich, defined waves that hold their pattern wash after wash. Deep Wave reads full at every length and pairs beautifully with an HD frontal.</p>',
  tags: ['virgin', 'deep wave', 'bundles'], isNew: true,
  options: { texture: ['deep-wave'], length: ['12', '14', '16', '18', '20', '22', '24', '26'] },
  price: (o) => lengthPrice(['12', '14', '16', '18', '20', '22', '24', '26'], N(90000), N(16000))[o.length],
  stock: () => 8, images: [['deep-wave-1.svg'], ['deep-wave-2.svg'], ['deep-wave-3.svg']], weight: 110,
  details: { origin: 'Ethically sourced virgin hair', grade: 'Signature', weight_per_bundle: '100g (±5g)' },
  collections: ['new-arrivals'],
});
product({
  name: 'HairverGreen Burmese Curly', slug: 'burmese-curly', sku: 'HG-BC', type: 'hair', cat: 'virgin-hair',
  short: 'Soft, springy curls with natural volume. Sold per bundle.',
  desc: '<p>Burmese Curly has a soft, springy curl that stays defined with a little water and a light leave-in. Full, bouncy and made for volume.</p>',
  tags: ['virgin', 'curly', 'bundles', 'burmese'], isNew: true,
  options: { texture: ['curly'], length: ['12', '14', '16', '18', '20', '22', '24'] },
  price: (o) => lengthPrice(['12', '14', '16', '18', '20', '22', '24'], N(95000), N(17000))[o.length],
  stock: () => 6, images: [['curly-1.svg'], ['curly-2.svg'], ['curly-3.svg']], weight: 110,
  details: { origin: 'Ethically sourced virgin hair', grade: 'Signature' }, collections: ['new-arrivals', 'limited-edition'],
});
product({
  name: 'HairverGreen Loose Wave', slug: 'loose-wave', sku: 'HG-LW', type: 'hair', cat: 'virgin-hair',
  short: 'Relaxed, lived-in waves between body and deep wave. Sold per bundle.',
  desc: '<p>An effortless, relaxed wave with movement and volume. Loose Wave is the easiest texture to wear straight from the pack.</p>',
  tags: ['virgin', 'loose wave', 'bundles'],
  options: { texture: ['loose-wave'], length: ['14', '16', '18', '20', '22', '24', '26'] },
  price: (o) => lengthPrice(['14', '16', '18', '20', '22', '24', '26'], N(95000), N(15000))[o.length],
  compare: (o) => lengthPrice(['14', '16', '18', '20', '22', '24', '26'], N(110000), N(15000))[o.length],
  stock: () => 9, images: [['loose-wave-1.svg'], ['loose-wave-2.svg'], ['loose-wave-3.svg']], weight: 110,
  details: { origin: 'Ethically sourced virgin hair', grade: 'Signature' }, collections: ['sale'],
});
product({
  name: 'HairverGreen Donor Hair Collection', slug: 'donor-hair-collection', sku: 'HG-DNR', type: 'hair', cat: 'donor-hair',
  short: 'Rare single-donor hair — the finest, most refined hair we carry. Sold per bundle.',
  desc: '<p>Each bundle comes from a single donor, so the strands share the same texture, thickness and age. The result is hair of exceptional softness and longevity — an investment piece that lasts for years with care.</p>',
  tags: ['donor', 'luxury', 'raw'], featured: true,
  options: { texture: ['straight', 'body-wave'], length: ['14', '16', '18', '20', '22', '24'] },
  price: (o) => lengthPrice(['14', '16', '18', '20', '22', '24'], N(165000), N(30000))[o.length] + (o.texture === 'body-wave' ? N(10000) : 0),
  stock: () => 4, images: [['straight-3.svg', { texture: 'straight' }], ['straight-4.svg', { texture: 'straight' }], ['body-wave-3.svg', { texture: 'body-wave' }], ['body-wave-4.svg', { texture: 'body-wave' }]], weight: 110,
  details: { origin: 'Single-donor hair', grade: 'Donor', hair_info: 'Unprocessed single-donor hair. Colour, texture and thickness are consistent across the bundle.' },
  collections: ['luxury', 'signature'],
});
product({
  name: 'HD Lace Closure', slug: 'hd-lace-closure', sku: 'HG-CLS', type: 'hair', cat: 'closures',
  short: 'Transparent HD lace closure, pre-plucked with bleached knots.',
  desc: '<p>Ultra-thin HD lace that melts into every skin tone. Pre-plucked with a natural hairline and lightly bleached knots for an invisible parting.</p>',
  tags: ['closure', 'hd lace'],
  options: { lace: ['4x4', '5x5', '6x6'], texture: ['straight', 'body-wave', 'deep-wave'], length: ['14', '16', '18'] },
  price: (o) => ({ '4x4': N(65000), '5x5': N(80000), '6x6': N(95000) }[o.lace] + (Number(o.length) - 14) * N(4000)),
  stock: () => 5,
  images: [['straight-2.svg', { texture: 'straight' }], ['body-wave-2.svg', { texture: 'body-wave' }], ['deep-wave-4.svg', { texture: 'deep-wave' }]], weight: 60,
  details: { lace_info: 'HD transparent lace. Pre-plucked hairline, bleached knots, free parting.' },
  collections: [],
});
product({
  name: 'HD Lace Frontal', slug: 'hd-lace-frontal', sku: 'HG-FRT', type: 'hair', cat: 'frontals',
  short: 'Ear-to-ear HD lace frontal, pre-plucked for a natural hairline.',
  desc: '<p>Our ear-to-ear HD frontal gives you parting freedom and an undetectable hairline. Pre-plucked and ready to customise.</p>',
  tags: ['frontal', 'hd lace'],
  options: { lace: ['13x4', '13x6'], texture: ['straight', 'body-wave', 'deep-wave'], length: ['16', '18', '20'] },
  price: (o) => ({ '13x4': N(95000), '13x6': N(125000) }[o.lace] + (Number(o.length) - 16) * N(5000)),
  stock: () => 4,
  images: [['straight-1.svg', { texture: 'straight' }], ['body-wave-4.svg', { texture: 'body-wave' }], ['deep-wave-3.svg', { texture: 'deep-wave' }]], weight: 70,
  details: { lace_info: 'HD transparent lace, 13" ear to ear. Pre-plucked hairline.' }, collections: [],
});
product({
  name: 'HairverGreen Ready-to-Wear Unit', slug: 'ready-to-wear-unit', sku: 'HG-RTW', type: 'wig', cat: 'ready-to-wear',
  short: 'Plucked, styled and ready to wear the day it arrives. 5×5 HD lace closure unit.',
  desc: '<p>Everything done for you: HD lace, pre-plucked hairline, bleached knots and a finished style. Put it on and go.</p>',
  tags: ['wig', 'ready to wear', 'bestseller'], featured: true,
  options: { texture: ['body-wave', 'straight'], length: ['16', '20', '24'], density: ['180', '200'] },
  price: (o) => N(380000) + (Number(o.length) - 16) * N(22000) + (o.density === '200' ? N(45000) : 0),
  stock: () => 3,
  images: [['body-wave-2.svg', { texture: 'body-wave' }], ['body-wave-1.svg', { texture: 'body-wave' }], ['straight-2.svg', { texture: 'straight' }], ['straight-4.svg', { texture: 'straight' }]], weight: 350,
  details: { construction: 'Closure (5×5 HD lace)', cap: 'Medium (22") with adjustable straps and combs', density_info: '180% for a natural look; 200% for extra fullness.' },
  collections: ['best-sellers', 'new-arrivals'],
});
product({
  name: 'HairverGreen Signature Glueless Unit', slug: 'signature-glueless-unit', sku: 'HG-GLU', type: 'wig', cat: 'glueless-wigs',
  short: 'Our signature glueless unit — secure without adhesive, natural at the hairline.',
  desc: '<p>A pre-cut HD lace, elastic band and pre-installed combs keep this unit secure without glue. Wear it in minutes, take it off without damage.</p>',
  tags: ['wig', 'glueless', 'bestseller'], featured: true,
  options: { texture: ['body-wave', 'straight', 'deep-wave'], length: ['14', '18', '22', '26'] },
  price: (o) => N(420000) + (Number(o.length) - 14) * N(25000),
  stock: (o) => (o.texture === 'deep-wave' && o.length === '26' ? 0 : 3),
  images: [['body-wave-1.svg', { texture: 'body-wave' }], ['straight-1.svg', { texture: 'straight' }], ['deep-wave-1.svg', { texture: 'deep-wave' }], ['editorial-3.svg']], weight: 350,
  details: { construction: 'Glueless · 5×5 HD lace', cap: 'Medium (22") with elastic band and combs', density_info: '200% density.' },
  collections: ['best-sellers', 'signature'],
});
product({
  name: 'Full Lace Luxury Unit', slug: 'full-lace-luxury-unit', sku: 'HG-FLL', type: 'wig', cat: 'lace-wigs',
  short: 'Full HD lace for 360° styling — high ponytails, updos and parting anywhere.',
  desc: '<p>The most versatile construction we make. Full lace lets you part and style anywhere, with a natural hairline all the way around.</p>',
  tags: ['wig', 'full lace', 'luxury'],
  options: { texture: ['straight'], length: ['20', '24', '28'], density: ['180', '220'] },
  price: (o) => N(780000) + (Number(o.length) - 20) * N(40000) + (o.density === '220' ? N(90000) : 0),
  stock: () => 2, images: [['straight-3.svg'], ['straight-4.svg'], ['editorial-3.svg']], weight: 380,
  details: { construction: 'Full lace (HD)', cap: 'Medium (22")' }, collections: ['luxury', 'limited-edition'],
});
product({
  name: 'The Sleek Bob', slug: 'the-sleek-bob', sku: 'HG-BOB', type: 'wig', cat: 'pre-styled-units',
  short: 'A precision-cut, pre-styled bob on a 5×5 HD closure.',
  desc: '<p>Cut and styled by our team into a clean, swinging bob. Minimal upkeep, maximum polish.</p>',
  tags: ['wig', 'bob', 'pre-styled'],
  options: { length: ['10', '12'], color: ['natural-black', 'chestnut-brown'] },
  price: (o) => N(265000) + (o.length === '12' ? N(20000) : 0) + (o.color === 'chestnut-brown' ? N(35000) : 0),
  compare: (o) => N(300000) + (o.length === '12' ? N(20000) : 0) + (o.color === 'chestnut-brown' ? N(35000) : 0),
  stock: () => 4, images: [['straight-4.svg'], ['straight-2.svg']], weight: 220,
  details: { construction: 'Closure (5×5 HD lace)', cap: 'Medium (22")' }, collections: ['sale', 'new-arrivals'],
});
product({
  name: 'Clip-In Extensions', slug: 'clip-in-extensions', sku: 'HG-CLP', type: 'hair', cat: 'hair-extensions',
  short: 'Seven-piece clip-in set for instant length and volume.',
  desc: '<p>A seven-piece set with silicone-lined clips that stay put without tugging. Add length and volume in minutes.</p>',
  tags: ['extensions', 'clip-in'],
  options: { texture: ['straight', 'kinky'], length: ['16', '20', '24'] },
  price: (o) => N(130000) + (Number(o.length) - 16) * N(12000),
  stock: () => 7, images: [['straight-2.svg', { texture: 'straight' }], ['kinky-1.svg', { texture: 'kinky' }], ['kinky-2.svg', { texture: 'kinky' }]], weight: 160,
  details: { hair_info: '7 pieces, 120g total. Silicone-lined clips.' }, collections: [],
});
product({
  name: 'HairverGreen Custom Unit', slug: 'custom-unit', sku: 'HG-CUSTOM', type: 'custom_unit', cat: 'custom-units',
  short: 'A unit made around you — texture, length, density, lace, colour and finish. Price shown is the starting price.',
  desc: '<p>Tell us exactly how you want to feel, and we will build it. Choose your hair, lace and finish, and our team will confirm every detail with you before production begins.</p>',
  tags: ['custom', 'wig', 'bespoke'], featured: false, requiresReview: true,
  options: {}, price: () => N(450000), stock: () => 0, track: false,
  images: [['custom-unit.svg'], ['editorial-1.svg']], weight: 400,
  details: { construction: 'Custom', production_time: '7–14 business days after confirmation' }, collections: ['signature'],
});
product({
  name: 'Wig Care Kit', slug: 'wig-care-kit', sku: 'HG-KIT', type: 'accessory', cat: 'accessories',
  short: 'Sulphate-free shampoo, conditioner, leave-in and a wide-tooth comb.',
  desc: '<p>Everything you need to keep your hair soft and lustrous between wears.</p>', tags: ['care', 'accessory'],
  options: {}, price: () => N(38000), stock: () => 25, images: [['care-kit.svg']], weight: 900, costRatio: 0.45, collections: [],
});
product({
  name: 'Silk Storage Bag', slug: 'silk-storage-bag', sku: 'HG-BAG', type: 'accessory', cat: 'accessories',
  short: 'A satin-lined storage bag with hanger to protect your unit between wears.',
  desc: '<p>Keeps your hair tangle-free and dust-free, and holds its shape on the hanger.</p>', tags: ['accessory', 'storage'],
  options: {}, price: () => N(18000), stock: () => 40, images: [['storage-bag.svg']], weight: 200, costRatio: 0.35, collections: [],
});
// Bundle deals
product({
  name: 'Build Your Bundle — 3 Bundles + Closure', slug: 'build-your-bundle', sku: 'HG-BYB', type: 'bundle_deal', cat: 'bundles',
  short: 'Choose three bundles in any length and a matching closure — and save 12% on the set.',
  desc: '<p>The complete install in one. Pick your three bundle lengths and your closure, and we will apply 12% off the total. Add a frontal for a further saving.</p>',
  tags: ['bundle deal', 'save'], featured: true,
  options: {}, price: () => 0, stock: () => 0, track: false, images: [['body-wave-3.svg'], ['deep-wave-2.svg']], weight: 0,
  bundle: { mode: 'percent_off', value: 12, headline: 'Save 12% on the complete set', items: [
    { product: 'signature-body-wave', qty: 1, label: 'Bundle 1' }, { product: 'signature-body-wave', qty: 1, label: 'Bundle 2' },
    { product: 'signature-body-wave', qty: 1, label: 'Bundle 3' }, { product: 'hd-lace-closure', qty: 1, label: 'Closure' },
    { product: 'hd-lace-frontal', qty: 1, label: 'Add a frontal', optional: true },
  ] }, collections: ['bundles', 'best-sellers'],
});
product({
  name: 'The Glueless Essentials Set', slug: 'glueless-essentials-set', sku: 'HG-GES', type: 'bundle_deal', cat: 'glueless-wigs',
  short: 'Signature Glueless Unit (Body Wave, 18") with the Wig Care Kit and Silk Storage Bag.',
  desc: '<p>Our best-selling glueless unit with everything you need to care for it — at a set price.</p>',
  tags: ['bundle deal', 'glueless', 'gift'],
  options: {}, price: () => N(485000), stock: () => 0, track: false, images: [['body-wave-1.svg'], ['care-kit.svg'], ['storage-bag.svg']], weight: 0,
  bundle: { mode: 'fixed', value: 0, headline: 'Wig + Care Kit + Storage Bag', items: [
    { product: 'signature-glueless-unit', variant: { texture: 'body-wave', length: '18' }, qty: 1 },
    { product: 'wig-care-kit', qty: 1 }, { product: 'silk-storage-bag', qty: 1 },
  ] }, collections: ['bundles'],
});

function combos(options) {
  const keys = Object.keys(options);
  if (!keys.length) return [{}];
  let res = [{}];
  for (const k of keys) res = res.flatMap((r) => options[k].map((v) => ({ ...r, [k]: v })));
  return res;
}
const labelOf = (k, v) => (attrs[k]?.find((a) => a[1] === v)?.[0]) ?? v;

const commonDetails = { care, shipping_note: shippingNote, returns_note: returnsNote, faq: faq() };
const payload = P.map((p) => {
  const vs = combos(p.options);
  return {
    n: p.name, s: p.slug, k: p.sku, t: p.type, c: p.cat, sh: p.short, d: p.desc, dt: p.details || {},
    tg: [...p.tags, 'demo'], ok: Object.keys(p.options), f: !!p.featured, nw: !!p.isNew, rr: !!p.requiresReview, w: p.weight,
    mp: Math.min(...vs.map((o) => p.price(o))),
    v: vs.map((o) => {
      const price = p.price(o);
      const track = p.track !== false;
      return [
        [p.sku, ...Object.values(o).map((x) => x.toUpperCase().replace(/[^A-Z0-9]/g, ''))].join('-'),
        Object.keys(o).length ? Object.entries(o).map(([k, x]) => labelOf(k, x)).join(' / ') : 'Default',
        o, price, p.compare ? p.compare(o) : null,
        track && p.type !== 'bundle_deal' ? Math.round(price * (p.costRatio ?? 0.55)) : null,
        track, track ? p.stock(o) : 0,
      ];
    }),
    m: p.images.map(([file, match]) => [file, match || {}]),
  };
});
sql(`do $seed$
declare common jsonb := ${j(commonDetails)}; p jsonb; v jsonb; m jsonb; pid uuid; i int; pos int;
begin
  for p in select * from jsonb_array_elements(${j(payload)}) loop
    insert into public.products (name, slug, sku, product_type, category_id, status, short_description, description, details, tags, option_keys,
      price, is_featured, is_new, requires_review, weight_grams, seo_description)
    values (p->>'n', p->>'s', p->>'k', p->>'t', (select id from public.categories where slug = p->>'c'), 'active', p->>'sh', p->>'d',
      common || (p->'dt'), array(select jsonb_array_elements_text(p->'tg')), array(select jsonb_array_elements_text(p->'ok')),
      (p->>'mp')::bigint, (p->>'f')::boolean, (p->>'nw')::boolean, (p->>'rr')::boolean, (p->>'w')::int, p->>'sh')
    returning id into pid;
    pos := 0;
    for v in select * from jsonb_array_elements(p->'v') loop
      insert into public.product_variants (product_id, sku, title, options, price, compare_at_price, cost_price, position, track_inventory, stock_on_hand, weight_grams, low_stock_threshold)
      values (pid, v->>0, v->>1, v->2, (v->>3)::bigint, nullif(v->>4,'')::bigint, nullif(v->>5,'')::bigint, pos, (v->>6)::boolean, (v->>7)::int, (p->>'w')::int, 2);
      pos := pos + 1;
    end loop;
    i := 0;
    for m in select * from jsonb_array_elements(p->'m') loop
      insert into public.product_media (product_id, media_id, option_match, sort)
      values (pid, (select id from public.media where filename = m->>0), m->1, i);
      i := i + 1;
    end loop;
  end loop;
end $seed$;`);
// Record initial stock as movements
sql(`insert into public.inventory_movements (variant_id, delta_on_hand, reason, note)
select id, stock_on_hand, 'adjustment', 'Initial demo stock' from public.product_variants where track_inventory and stock_on_hand > 0;`);

// Bundles
for (const p of P.filter((x) => x.bundle)) {
  sql(`insert into public.bundles (product_id, pricing_mode, value, headline) values ((select id from public.products where slug = ${q(p.slug)}), ${q(p.bundle.mode)}, ${p.bundle.value}, ${q(p.bundle.headline)});`);
  p.bundle.items.forEach((it, s) => sql(`insert into public.bundle_items (bundle_product_id, product_id, variant_id, quantity, is_optional, label, sort)
values ((select id from public.products where slug = ${q(p.slug)}), (select id from public.products where slug = ${q(it.product)}),
  ${it.variant ? `(select v.id from public.product_variants v join public.products pp on pp.id = v.product_id where pp.slug = ${q(it.product)} and v.options @> ${j(it.variant)} limit 1)` : 'null'},
  ${it.qty}, ${!!it.optional}, ${q(it.label ?? null)}, ${s});`));
}

// Relations
const rel = (a, b, kind) => sql(`insert into public.product_relations (product_id, related_id, kind) select a.id, b.id, ${q(kind)} from public.products a, public.products b where a.slug = ${q(a)} and b.slug = ${q(b)} on conflict do nothing;`);
for (const s of ['signature-body-wave', 'luxury-straight', 'deep-wave', 'burmese-curly', 'loose-wave', 'donor-hair-collection']) {
  rel(s, 'hd-lace-closure', 'bought_together'); rel(s, 'hd-lace-frontal', 'bought_together'); rel(s, 'wig-care-kit', 'cross_sell');
  rel(s, 'build-your-bundle', 'upsell');
}
for (const s of ['ready-to-wear-unit', 'signature-glueless-unit', 'full-lace-luxury-unit', 'the-sleek-bob']) {
  rel(s, 'wig-care-kit', 'bought_together'); rel(s, 'silk-storage-bag', 'bought_together'); rel(s, 'glueless-essentials-set', 'upsell');
}
[['signature-body-wave', 'loose-wave'], ['signature-body-wave', 'deep-wave'], ['luxury-straight', 'donor-hair-collection'], ['ready-to-wear-unit', 'signature-glueless-unit'], ['signature-glueless-unit', 'full-lace-luxury-unit'], ['deep-wave', 'burmese-curly']]
  .forEach(([a, b]) => { rel(a, b, 'related'); rel(b, a, 'related'); });

// Collections
const cols = [
  ['Best Sellers', 'best-sellers', 'The pieces our clients return to.', 'body-wave-2.svg', true],
  ['New Arrivals', 'new-arrivals', 'Just landed in the Lagos studio.', 'deep-wave-2.svg', true],
  ['The Signature Collection', 'signature', 'The textures and units that define Hairver Green.', 'editorial-1.svg', true],
  ['The Luxury Collection', 'luxury', 'Donor hair and full lace — our most refined pieces.', 'editorial-3.svg', false],
  ['Sale', 'sale', 'Selected pieces, for a limited time.', 'loose-wave-2.svg', false],
  ['Bundle Deals', 'bundles', 'Complete sets, priced together.', 'body-wave-3.svg', false],
  ['Limited Edition', 'limited-edition', 'Small runs. When they are gone, they are gone.', 'curly-2.svg', false],
];
cols.forEach(([n, s, t, img, f], i) => sql(`insert into public.collections (name, slug, tagline, description, image_id, is_featured, sort, seo_description)
values (${q(n)}, ${q(s)}, ${q(t)}, ${q(t)}, ${M(img)}, ${f}, ${i}, ${q(t)});`));
for (const p of P) (p.collections || []).forEach((c, i) => sql(`insert into public.collection_products (collection_id, product_id, sort) select c.id, p.id, ${i} from public.collections c, public.products p where c.slug = ${q(c)} and p.slug = ${q(p.slug)};`));
sql(`update public.collections set deal_enabled = true, deal_price = ${N(1150000)} where slug = 'signature';`);

// Sample reviews (clearly labelled — delete or replace with real customer reviews)
const reviews = [
  ['signature-body-wave', 5, 'Sample review', 'This is a sample review so you can see how reviews display. Replace it with real customer reviews from Admin → Reviews.'],
  ['signature-glueless-unit', 5, 'Sample review', 'Sample review text. Real reviews are submitted by customers after purchase and approved by your team.'],
  ['luxury-straight', 4, 'Sample review', 'Sample review text showing a four-star rating. Delete from Admin → Reviews before launch.'],
];
reviews.forEach(([slug, r, name, body]) => sql(`insert into public.reviews (product_id, author_name, rating, title, body, status, is_verified)
select id, ${q(name)}, ${r}, 'Sample', ${q(body)}, 'approved', false from public.products where slug = ${q(slug)};`));

// ---------------------------------------------------------------------------
// Discounts
// ---------------------------------------------------------------------------
sql(`insert into public.discounts (name, code, description, kind, value, eligibility, per_customer_limit, is_active)
values ('Welcome 10% off', 'WELCOME10', '10% off your first order', 'percentage', 10, 'new', 1, true);`);
sql(`insert into public.discounts (name, code, description, kind, value, applies_to, min_subtotal, countries, is_active)
values ('Free Nigeria shipping', 'SHIPFREE', 'Free delivery within Nigeria on orders over ₦300,000', 'free_shipping', 0, 'order', ${N(300000)}, array['NG'], true);`);
sql(`insert into public.discounts (name, code, description, kind, applies_to, target_ids, tiers, is_active)
values ('Buy more, save more (bundles)', null, 'Save 5% on 2 bundles and 10% on 3 or more', 'tiered', 'categories',
  array[(select id from public.categories where slug = 'virgin-hair'), (select id from public.categories where slug = 'donor-hair')],
  '[{"min_qty":2,"percent":5},{"min_qty":3,"percent":10}]'::jsonb, true);`);

// ---------------------------------------------------------------------------
// Shipping & tax (demo rates — set real rates in Admin → Shipping)
// ---------------------------------------------------------------------------
const zones = [
  ['Lagos', ['NG'], ['Lagos'], [
    ['Standard delivery', 'Dispatch rider', 'standard', N(5000), N(400000), 1, 2], ['Same-day express', 'Dispatch rider', 'express', N(10000), null, 0, 1], ['Studio pickup (Lagos)', null, 'pickup', 0, null, 0, 1]]],
  ['Abuja', ['NG'], ['FCT', 'Abuja'], [['Standard delivery', 'GIG Logistics', 'standard', N(8000), N(400000), 2, 3], ['Express', 'DHL', 'express', N(18000), null, 1, 2]]],
  ['Rest of Nigeria', ['NG'], [], [['Standard delivery', 'GIG Logistics', 'standard', N(10000), N(400000), 3, 5], ['Express', 'DHL', 'express', N(22000), null, 1, 3]]],
  ['Africa', ['GH', 'KE', 'ZA', 'CI', 'SN', 'RW', 'UG', 'TZ', 'CM', 'BJ', 'TG'], [], [['International express', 'DHL Express', 'express', N(85000), null, 4, 7]]],
  ['United Kingdom', ['GB'], [], [['International express', 'DHL Express', 'express', N(95000), N(2500000), 3, 6]]],
  ['United States & Canada', ['US', 'CA'], [], [['International express', 'DHL Express', 'express', N(110000), N(2500000), 4, 7]]],
  ['Europe', ['DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'IE', 'PT', 'SE', 'DK', 'NO', 'CH', 'AT', 'PL', 'FI'], [], [['International express', 'DHL Express', 'express', N(100000), null, 4, 8]]],
  ['Rest of World', ['*'], [], [['International express', 'DHL Express', 'express', N(130000), null, 5, 10]]],
];
zones.forEach(([name, countries, states, methods], i) => {
  sql(`insert into public.shipping_zones (name, countries, states, sort) values (${q(name)}, ${arr(countries)}, ${arr(states)}, ${i});`);
  methods.forEach(([m, carrier, lvl, rate, free, mn, mx], s) => sql(`insert into public.shipping_methods (zone_id, name, carrier, service_level, rate_type, base_rate, free_over, min_days, max_days, sort, per_kg_rate)
values ((select id from public.shipping_zones where name = ${q(name)}), ${q(m)}, ${q(carrier)}, ${q(lvl)}, ${lvl === 'express' && i >= 3 ? "'weight'" : "'flat'"}, ${rate}, ${q(free)}, ${mn}, ${mx}, ${s}, ${lvl === 'express' && i >= 3 ? N(15000) : 0});`));
});
sql(`insert into public.tax_rules (name, country, rate_percent, is_active) values ('Nigeria VAT (inactive — prices include VAT)', 'NG', 7.5, false);`);

// ---------------------------------------------------------------------------
// Navigation
// ---------------------------------------------------------------------------
const main = [
  { label: 'New Arrivals', href: '/collections/new-arrivals' },
  { label: 'Wigs', href: '/wigs', children: [
    { label: 'Ready-to-Wear Wigs', href: '/wigs/ready-to-wear' }, { label: 'Glueless Wigs', href: '/wigs/glueless-wigs' },
    { label: 'Lace Wigs', href: '/wigs/lace-wigs' }, { label: 'Custom Units', href: '/services/custom-units' }, { label: 'Pre-Styled Units', href: '/wigs/pre-styled-units' }],
    feature: { title: 'The Glueless Edit', href: '/wigs/glueless-wigs', image: '/demo/body-wave-1.svg' } },
  { label: 'Hair', href: '/hair', children: [
    { label: 'Virgin Hair', href: '/hair/virgin-hair' }, { label: 'Donor Hair', href: '/hair/donor-hair' }, { label: 'Bundles', href: '/hair/bundles' },
    { label: 'Closures', href: '/hair/closures' }, { label: 'Frontals', href: '/hair/frontals' }, { label: 'Hair Extensions', href: '/hair/hair-extensions' }],
    feature: { title: 'Donor Hair', href: '/hair/donor-hair', image: '/demo/straight-3.svg' } },
  { label: 'Shop by Texture', href: '/shop', auto: 'texture' },
  { label: 'Shop by Length', href: '/shop', auto: 'length' },
  { label: 'Collections', href: '/collections', children: [
    { label: 'Best Sellers', href: '/collections/best-sellers' }, { label: 'New Arrivals', href: '/collections/new-arrivals' },
    { label: 'Signature Collection', href: '/collections/signature' }, { label: 'Luxury Collection', href: '/collections/luxury' },
    { label: 'Sale', href: '/collections/sale' }, { label: 'Bundle Deals', href: '/collections/bundles' }, { label: 'Limited Edition', href: '/collections/limited-edition' }] },
  { label: 'Services', href: '/services/custom-units', children: [
    { label: 'Custom Units', href: '/services/custom-units' }, { label: 'Wig Customisation', href: '/services/consultation?type=service' },
    { label: 'Hair Services', href: '/services/consultation?type=service' }, { label: 'Book a Consultation', href: '/services/consultation' }] },
  { label: 'Hair Guide', href: '/hair-guide' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];
const menus = {
  main: ['Main navigation', main],
  footer_shop: ['Footer · Shop', [{ label: 'Wigs', href: '/wigs' }, { label: 'Hair', href: '/hair' }, { label: 'New Arrivals', href: '/collections/new-arrivals' }, { label: 'Best Sellers', href: '/collections/best-sellers' }, { label: 'Collections', href: '/collections' }, { label: 'Sale', href: '/collections/sale' }]],
  footer_care: ['Footer · Customer Care', [{ label: 'Contact', href: '/contact' }, { label: 'Shipping', href: '/policies/shipping-policy' }, { label: 'Returns', href: '/policies/refund-policy' }, { label: 'FAQ', href: '/faq' }, { label: 'Track Order', href: '/track-order' }]],
  footer_brand: ['Footer · Hairver Green', [{ label: 'About', href: '/about' }, { label: 'Hair Journal', href: '/journal' }, { label: 'Custom Units', href: '/services/custom-units' }, { label: 'Services', href: '/services/consultation' }, { label: 'Hair Guide', href: '/hair-guide' }]],
  footer_legal: ['Footer · Legal', [{ label: 'Privacy', href: '/policies/privacy-policy' }, { label: 'Terms', href: '/policies/terms' }, { label: 'Refund Policy', href: '/policies/refund-policy' }, { label: 'Shipping Policy', href: '/policies/shipping-policy' }, { label: 'Cookie Policy', href: '/policies/cookie-policy' }]],
};
sql(`insert into public.menus (key, name, items) values\n${Object.entries(menus).map(([k, [n, items]]) => `(${q(k)}, ${q(n)}, ${j(items)})`).join(',\n')};`);

// ---------------------------------------------------------------------------
// Pages & homepage sections
// ---------------------------------------------------------------------------
const page = (slug, title, kind, body, seo) => sql(`insert into public.pages (slug, title, kind, status, body, seo_description, published_at) values (${q(slug)}, ${q(title)}, ${q(kind)}, 'published', ${q(body)}, ${q(seo)}, now());`);
page('home', 'Home', 'home', null, 'Premium virgin hair, donor hair, custom units and ready-to-wear wigs, crafted in Lagos and delivered worldwide.');
const sections = [
  ['hero', 'Hero', { layout: 'split', font: 'editorial', eyebrow: 'Luxury Hair House · Lagos', heading: 'Luxury hair. *Beautifully* yours.', text: 'Premium virgin hair, donor hair, custom units and ready-to-wear wigs, crafted for effortless beauty.',
    media: { kind: 'image', url: '/hero/hero-curly.jpg', alt: 'Model wearing voluminous curly hair' }, focal: '50% 20%',
    ctas: [{ label: 'Shop wigs', href: '/wigs', style: 'primary' }, { label: 'Shop hair', href: '/hair', style: 'secondary' }],
    trust: [{ text: 'Hand-finished in Lagos' }, { text: 'Virgin & single-donor hair' }, { text: 'Tracked worldwide shipping' }],
    feature_product: 'burmese-curly', feature_eyebrow: 'Worn here · New', theme: 'dark' }],
  ['category_grid', 'Featured categories', { heading: 'Find your hair', eyebrow: 'Shop', items: [
    { label: 'Ready-to-Wear', href: '/wigs/ready-to-wear', image: '/demo/body-wave-2.svg' }, { label: 'Custom Units', href: '/services/custom-units', image: '/demo/custom-unit.svg' },
    { label: 'Virgin Hair', href: '/hair/virgin-hair', image: '/demo/body-wave-1.svg' }, { label: 'Donor Hair', href: '/hair/donor-hair', image: '/demo/straight-3.svg' }], layout: 'grid-4' }],
  ['product_carousel', 'Best sellers', { heading: 'Best sellers', eyebrow: 'Most loved', source: 'collection', collection: 'best-sellers', limit: 8, cta: { label: 'Shop best sellers', href: '/collections/best-sellers' } }],
  ['editorial', 'From Lagos, for the world', { eyebrow: 'Hairver Green', heading: 'From Lagos, for the world.', text: 'Discover premium hair crafted with intention and delivered wherever you are.',
    media: { kind: 'image', url: '/demo/editorial-1.svg', alt: '' }, cta: { label: 'Explore Hairver Green', href: '/about' }, layout: 'image-left', background: 'panel' }],
  ['product_carousel', 'New arrivals', { heading: 'New arrivals', eyebrow: 'Just landed', source: 'collection', collection: 'new-arrivals', limit: 8, cta: { label: 'Shop new arrivals', href: '/collections/new-arrivals' } }],
  ['shop_the_look', 'Shop the look', { heading: 'Shop the look', eyebrow: 'Editorial', media: { kind: 'image', url: '/demo/editorial-2.svg', alt: '' }, products: ['signature-glueless-unit', 'wig-care-kit', 'silk-storage-bag'], text: 'Our Signature Glueless Unit, finished and styled — with everything you need to keep it that way.' }],
  ['collection_feature', 'Signature collection', { eyebrow: 'The Signature Collection', heading: 'Made to be noticed.', text: 'The textures and units that define Hairver Green — selected, finished and checked by hand in our Lagos studio.',
    collection: 'signature', media: { kind: 'image', url: '/demo/editorial-3.svg', alt: '' }, cta: { label: 'Discover the collection', href: '/collections/signature' }, theme: 'dark' }],
  ['value_props', 'Why Hairver Green', { heading: 'Why Hairver Green', items: [
    { title: 'Premium hair', text: 'Virgin and single-donor hair, selected strand by strand.', icon: 'sparkle' },
    { title: 'Expert craftsmanship', text: 'Every unit is constructed, plucked and finished by hand in Lagos.', icon: 'scissors' },
    { title: 'Global shipping', text: 'Tracked delivery across Nigeria and worldwide.', icon: 'globe' },
    { title: 'Personal service', text: 'Real people, on hand to help you choose.', icon: 'heart' }] }],
  ['process_steps', 'Custom unit experience', { eyebrow: 'Custom units', heading: 'Crafted around you.', text: 'A unit built to your measurements, texture and style — confirmed with you at every step.',
    steps: [{ title: 'Consultation', text: 'Tell us the look and feel you want.' }, { title: 'Selection', text: 'Choose your hair, lace and density.' }, { title: 'Customisation', text: 'Colour, parting, plucking and finish.' }, { title: 'Crafting', text: 'Built by hand in our Lagos studio.' }, { title: 'Delivery', text: 'Styled, checked and sent to you.' }],
    media: { kind: 'image', url: '/demo/custom-unit.svg', alt: '' }, cta: { label: 'Create your custom unit', href: '/services/custom-units' } }],
  ['reviews', 'Customer reviews', { heading: 'In their words', eyebrow: 'Reviews', limit: 8 }],
  ['social_gallery', 'Social gallery', { heading: 'Follow the Hairver Green world', eyebrow: '@hairvergreen', cta: { label: 'Follow on Instagram', href: 'https://www.instagram.com/hairvergreen/' } }],
  ['journal', 'Hair journal', { heading: 'The Hair Journal', eyebrow: 'Read', limit: 3, cta: { label: 'Read the journal', href: '/journal' } }],
  ['newsletter', 'Newsletter', { heading: 'Be the first to know.', text: 'Join the Hairver Green list for new drops, exclusive offers and hair care tips.', theme: 'dark' }],
];
sections.forEach(([type, name, settings], i) => sql(`insert into public.page_sections (page_id, type, name, sort, settings) values ((select id from public.pages where slug = 'home'), ${q(type)}, ${q(name)}, ${i}, ${j(settings)});`));

page('about', 'About', 'page', null, 'Hairver Green is a luxury hair house in Lagos, Nigeria.');
[
  ['hero', 'About hero', { eyebrow: 'Our story', heading: 'A luxury hair house, born in Lagos.', text: 'We make hair for women who know exactly how they want to feel.', media: { kind: 'image', url: '/demo/editorial-3.svg', alt: '' }, height: 'medium', align: 'center', overlay: 0.3, theme: 'dark' }],
  ['rich_text', 'Story', { html: '<p><em>Replace this with the Hairver Green story.</em> Use this space to share how the brand began, who is behind it and what you believe beautiful hair should feel like.</p><p>Talk about how you select your hair, how units are made in your Lagos studio, and the care you put into every order that leaves it.</p>', width: 'narrow' }],
  ['value_props', 'Values', { heading: 'What we stand for', items: [{ title: 'Authenticity', text: 'Honest descriptions of every texture, grade and origin.' }, { title: 'Craft', text: 'Hand-finished units, checked before they leave the studio.' }, { title: 'Care', text: 'Guidance before and after you buy.' }] }],
  ['newsletter', 'Newsletter', { heading: 'Stay close.', text: 'New drops, offers and hair care notes — straight to your inbox.', theme: 'dark' }],
].forEach(([type, name, settings], i) => sql(`insert into public.page_sections (page_id, type, name, sort, settings) values ((select id from public.pages where slug = 'about'), ${q(type)}, ${q(name)}, ${i}, ${j(settings)});`));

page('hair-guide', 'Hair Guide', 'page', null, 'How to choose texture, length, lace and density — the Hairver Green hair guide.');
[
  ['hero', 'Guide hero', { eyebrow: 'Hair guide', heading: 'Choose with confidence.', text: 'Texture, length, lace and density — explained simply.', media: { kind: 'image', url: '/demo/editorial-1.svg', alt: '' }, height: 'short', align: 'center', overlay: 0.35, theme: 'dark' }],
  ['texture_guide', 'Texture guide', { heading: 'Texture guide', eyebrow: 'Compare' }],
  ['length_guide', 'Length guide', { heading: 'Length guide', text: 'Lengths are measured straight, from the top of the weft to the tips. Curly and wavy textures will look shorter than their stretched length.' }],
  ['faq', 'Lace & density', { heading: 'Lace, density & construction', items: [
    { q: 'What is the difference between a closure and a frontal?', a: 'A closure is a square piece of lace (4×4, 5×5 or 6×6) that covers the parting area. A frontal runs ear to ear (13×4 or 13×6), giving you a full hairline and more parting freedom.' },
    { q: 'What does HD lace mean?', a: 'HD lace is an ultra-thin, transparent Swiss lace that blends with every skin tone and is almost invisible on the skin.' },
    { q: 'Which density should I choose?', a: '150% is light and natural, 180% is our most popular everyday fullness, and 200–220% gives a full, glamorous look.' },
    { q: 'What is a glueless unit?', a: 'A unit designed to be worn without adhesive. It uses an elastic band, combs and a pre-cut lace so you can wear it securely and remove it without damage.' },
    { q: 'How many bundles do I need?', a: 'For a full sew-in, we recommend three bundles for 10"–20", and three to four bundles for 22" and longer, plus a closure or frontal.' }] }],
  ['rich_text', 'Care', { heading: 'Hair care', html: '<p>Detangle gently from ends to roots with a wide-tooth comb. Co-wash every 7–10 wears with a sulphate-free shampoo and moisturising conditioner. Air-dry flat or on a stand, use heat protectant before styling, and store your unit in a silk bag.</p>', width: 'narrow' }],
].forEach(([type, name, settings], i) => sql(`insert into public.page_sections (page_id, type, name, sort, settings) values ((select id from public.pages where slug = 'hair-guide'), ${q(type)}, ${q(name)}, ${i}, ${j(settings)});`));

page('faq', 'FAQ', 'page', null, 'Frequently asked questions about Hairver Green orders, shipping and hair care.');
sql(`insert into public.page_sections (page_id, type, name, sort, settings) values ((select id from public.pages where slug = 'faq'), 'faq', 'FAQ', 0, ${j({ heading: 'Frequently asked questions', items: [
  { q: 'How do I pay?', a: 'Checkout is secured by Paystack. Depending on availability you can pay by card, bank transfer, USSD, bank account and other supported channels.' },
  { q: 'Do you ship internationally?', a: 'Yes. Shipping options and costs for your country are shown at checkout.' },
  { q: 'How do I track my order?', a: 'You will receive tracking details by email when your order ships. You can also use the Track Order page or your account.' },
  { q: 'Can I return my hair?', a: 'Please read our Refund Policy for eligibility. Worn, cut, coloured or custom items cannot be returned.' },
  { q: 'How long do custom units take?', a: 'Custom units are made to order. We confirm your configuration and timeline with you before production begins.' }] })});`);

const policy = (slug, title) => page(slug, title, 'policy',
  `<p><strong>Placeholder — replace with Hairver Green's actual ${title.toLowerCase()} before launch.</strong> Edit this page in Admin → Content → Pages.</p><p>Every statement on this page should reflect a real Hairver Green policy.</p>`, `${title} for Hairver Green.`);
policy('privacy-policy', 'Privacy Policy'); policy('terms', 'Terms of Service'); policy('refund-policy', 'Refund Policy');
policy('shipping-policy', 'Shipping Policy'); policy('cookie-policy', 'Cookie Policy');

// ---------------------------------------------------------------------------
// Journal
// ---------------------------------------------------------------------------
const bcats = ['Hair Care', 'Wig Care', 'Hair Guides', 'Styling', 'Beauty', 'Trends', 'Hair Education', 'Hairver Green Stories'];
sql(`insert into public.blog_categories (name, slug, sort) values ${bcats.map((c, i) => `(${q(c)}, ${q(c.toLowerCase().replace(/\s+/g, '-'))}, ${i})`).join(', ')};`);
const posts = [
  ['how-to-choose-your-density', 'How to choose the right density', 'hair-guides', 'journal-1.svg', 'Density is the single biggest factor in how natural — or how glamorous — your unit looks. Here is how to choose.',
    '<p>Density describes how much hair is ventilated onto the cap. It is the difference between a unit that looks like it grew from your scalp and one that turns heads from across the room.</p><h2>150% — natural and light</h2><p>Closest to most people\'s natural hair. Comfortable in warm weather and ideal for shorter lengths.</p><h2>180% — everyday fullness</h2><p>Our most popular choice. Full enough to look polished, light enough to wear all day.</p><h2>200–220% — full glamour</h2><p>For volume and drama, especially on longer lengths where hair naturally thins towards the ends.</p><h2>A simple rule</h2><p>The longer the length, the more density you will want to keep the ends looking full.</p>', ['ready-to-wear-unit', 'signature-glueless-unit']],
  ['caring-for-body-wave-hair', 'Caring for body wave hair', 'hair-care', 'journal-2.svg', 'Keep your body wave soft, defined and tangle-free for longer with this simple routine.',
    '<p>Body wave is our signature texture for a reason — it is soft, versatile and forgiving. A few habits keep it that way.</p><h2>Wash less, condition more</h2><p>Co-wash every 7–10 wears with a sulphate-free shampoo, and always follow with a moisturising conditioner.</p><h2>Detangle from the ends</h2><p>Use a wide-tooth comb and work upwards from the ends to the roots, holding the hair above the section you are combing.</p><h2>Let the pattern come back</h2><p>After washing, rake a light leave-in through with your fingers and let it air-dry. The wave returns on its own.</p>', ['signature-body-wave', 'wig-care-kit']],
  ['closure-vs-frontal', 'Closure or frontal: which is right for you?', 'hair-education', 'journal-3.svg', 'Both give you a natural parting — the difference is how much freedom you want.',
    '<p>Closures and frontals both finish an install with a natural-looking parting. The choice comes down to how you like to style.</p><h2>Closures</h2><p>A 4×4, 5×5 or 6×6 square of lace that covers the parting area. Lower maintenance and easy to install.</p><h2>Frontals</h2><p>A 13×4 or 13×6 lace that runs ear to ear. It gives a full hairline, so you can part anywhere and wear the hair off your face.</p>', ['hd-lace-closure', 'hd-lace-frontal']],
  ['welcome-to-hairver-green', 'Welcome to Hairver Green', 'hairver-green-stories', 'journal-4.svg', 'A luxury hair house, from Lagos to wherever life takes you.',
    '<p><em>Replace this post with your own story.</em> This is where you can introduce the Hairver Green studio, the people behind it and the craft that goes into every piece.</p>', []],
];
posts.forEach(([slug, title, cat, img, excerpt, body, prods], i) => sql(`insert into public.blog_posts (slug, title, excerpt, body, category_id, featured_image_id, author_name, status, published_at, related_product_ids, reading_minutes, seo_description, tags)
values (${q(slug)}, ${q(title)}, ${q(excerpt)}, ${q(body)}, (select id from public.blog_categories where slug = ${q(cat)}), ${M(img)}, 'Hairver Green Editorial', 'published', now() - interval '${(i + 1) * 5} days',
  coalesce((select array_agg(id) from public.products where slug = any(${arr(prods)})), '{}'), 3, ${q(excerpt)}, ${arr(['demo'])});`));

// ---------------------------------------------------------------------------
// Popups, announcements, social
// ---------------------------------------------------------------------------
sql(`insert into public.popups (name, kind, title, body, image_id, cta_label, coupon_code, collect_email, trigger, delay_seconds, frequency_days, audience, is_active, style)
values ('Welcome offer', 'welcome', 'Get 10% off your first order', 'Join the Hairver Green list for new drops, exclusive offers and hair care notes. Your code arrives instantly.', ${M('editorial-1.svg')}, 'Unlock 10% off', 'WELCOME10', true, 'delay', 12, 14, 'new_visitors', true, '{"layout":"split","background":"ivory","animation":"fade"}'::jsonb);`);
sql(`insert into public.announcements (message, href, sort) values
('Global shipping available — from Lagos to wherever you are', '/policies/shipping-policy', 0),
('Free Lagos delivery on orders over ₦400,000', '/policies/shipping-policy', 1),
('New drop — Burmese Curly is here', '/products/burmese-curly', 2);`);
for (let i = 1; i <= 8; i++) {
  const prods = [['signature-body-wave'], ['signature-glueless-unit'], ['luxury-straight'], ['deep-wave'], ['burmese-curly'], ['ready-to-wear-unit'], ['donor-hair-collection'], ['the-sleek-bob']][i - 1];
  sql(`insert into public.social_posts (platform, media_id, image_url, permalink, caption, product_ids, sort)
values ('instagram', ${M(`social-${i}.svg`)}, '/demo/social-${i}.svg', 'https://www.instagram.com/hairvergreen/', 'Demo post — link real posts in Admin → Social', coalesce((select array_agg(id) from public.products where slug = any(${arr(prods)})), '{}'), ${i});`);
}

// Campaign example
sql(`insert into public.campaigns (name, slug, description, status, starts_at, ends_at)
values ('Black Friday 2026', 'black-friday-2026', 'Example campaign — set products, discounts, banner and landing page.', 'draft', '2026-11-27 00:00+01', '2026-11-30 23:59+01');`);

writeFileSync(join(process.cwd(), 'supabase', 'seed.sql'), out.join('\n'));
console.log(`seed.sql written (${out.length} statements, ${P.length} products)`);
